---
title: "Tugas Modul 4"
author: "Shania"
date: "2022-09-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dslabs)
data(murders)
```
## Nomor 1
```{r}
pop <- murders$population
pop<-sort(pop)
 
pop[1]
```
## Nomor 2
```{r}
pop <- murders$population
o <- order(pop)
o[1]
```
## Nomor 3
```{r}
which.min(murders$population)
```
## Nomor 4
```{r}
i <- which.min(murders$population)
states <- murders$state
states[i]
```
## Nomor 5
```{r}
temp <- c(35, 88, 42, 84, 81, 30)
city <- c("Beijing", "Lagos", "Paris", "Rio de Janeiro", "San Juan", "Toronto")
city_temps <- data.frame(name = city, temperature = temp)
states <- murders$state
 
ranks <- rank(murders$population)
my_df <- data.frame(name=states, ranks)
```
## Nomor 6
```{r}
states <- murders$state
ranks <- rank(murders$population)
ind <- order(murders$population)
my_df<-data.frame(states = states[ind], ranks = ranks[ind])
```
## Nomor 7
```{r}
population_in_millions <- murders$population/10^6
total_gun_murders <- murders$total
plot(population_in_millions, total_gun_murders)
log10_population <-log10(murders$population)
log10_total_gun_murders <- log10(total_gun_murders)
plot(log10_population,log10_total_gun_murders)
```
## Nomor 8
```{r}
population_in_millions <- murders$population/10^6
hist(population_in_millions)
```
## Nomor 9
```{r}
boxplot(population~region, data=murders)
```